version: "3.9"
 
services:
  web:
    container_name: pwa-scheduler-web
    hostname: pwa-scheduler-web
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    restart: unless-stopped
    command: npm run dev
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5173', (r) => r.statusCode !== 200 ? process.exit(1) : process.exit(0))"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

networks:
  app-network:
    driver: bridge